import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";

const poppins = Poppins({
    variable: "--font-geist-sans",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "ESI Maint",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <script crossOrigin="anonymous" src="//unpkg.com/react-scan/dist/auto.global.js" />
            </head>
            <body className={` ${poppins.className}   bg-isabelline h-screen`}>
                {children}
                <NextTopLoader crawlSpeed={100} />
                <Toaster />
            </body>
        </html>
    );
}
